-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 14:06:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pineValley
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_pineValley` ;

-- -----------------------------------------------------
-- Schema db_pineValley
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pineValley` DEFAULT CHARACTER SET utf8;
USE `db_pineValley` ;

-- -----------------------------------------------------
-- Table `db_pineValley`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pineValley`.`table1` ;

CREATE TABLE IF NOT EXISTS `db_pineValley`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pineValley`.`tblCustomer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pineValley`.`tblCustomer` ;

CREATE TABLE IF NOT EXISTS `db_pineValley`.`tblCustomer` (
  `idCust` INT NOT NULL AUTO_INCREMENT,
  `strCustName` VARCHAR(45) NOT NULL,
  `strAddress` VARCHAR(45) NULL,
  `strCity` VARCHAR(45) NULL,
  `strProvince` VARCHAR(45) NULL,
  `intZip` INT NULL,
  `strUserName` VARCHAR(45) NOT NULL,
  `strPasscode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCust`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pineValley`.`tblOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pineValley`.`tblOrder` ;

CREATE TABLE IF NOT EXISTS `db_pineValley`.`tblOrder` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `dtmOrderDate` DATE NOT NULL DEFAULT CURDATE(),
  `tblCustomer_idCust` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_tblOrder_tblCustomer_idx` (`tblCustomer_idCust` ASC) ,
  CONSTRAINT `fk_tblOrder_tblCustomer`
    FOREIGN KEY (`tblCustomer_idCust`)
    REFERENCES `db_pineValley`.`tblCustomer` (`idCust`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pineValley`.`tblProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pineValley`.`tblProduct` ;

CREATE TABLE IF NOT EXISTS `db_pineValley`.`tblProduct` (
  `idProd` INT NOT NULL AUTO_INCREMENT,
  `strDesc` VARCHAR(45) NOT NULL,
  `dtmFinish` DATE NOT NULL DEFAULT CURDATE(),
  `intPrice` INT NOT NULL,
  `intOnHand` INT NOT NULL,
  PRIMARY KEY (`idProd`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `db_pineValley`.`tblOrderLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pineValley`.`tblOrderLine` ;

CREATE TABLE IF NOT EXISTS `db_pineValley`.`tblOrderLine` (
  `intQuantity` INT NOT NULL,
  `tblOrder_idOrder` INT NOT NULL,
  `tblProduct_idProd` INT NOT NULL,
  INDEX `fk_tblOrderLine_tblOrder1_idx` (`tblOrder_idOrder` ASC) ,
  INDEX `fk_tblOrderLine_tblProduct1_idx` (`tblProduct_idProd` ASC) ,
  CONSTRAINT `fk_tblOrderLine_tblOrder1`
    FOREIGN KEY (`tblOrder_idOrder`)
    REFERENCES `db_pineValley`.`tblOrder` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblOrderLine_tblProduct1`
    FOREIGN KEY (`tblProduct_idProd`)
    REFERENCES `db_pineValley`.`tblProduct` (`idProd`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
